recipe_website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Recipe(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    recipe_name = db.Column(db.String(255))
    recipe_description = db.Column(db.String(10000))
    recipe_ingredients = db.Column(db.String(10000))
    recipe_instructions = db.Column(db.String(10000))
    # recipe_image = db.Column(db.String(150)) to-do - add image
    date = db.Column(db.DateTime(timezone=True), default=db.func.now()) # default - automatically set the date and time
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class User(db.Model, UserMixin): # UserMixin - flask login - current_user
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    username = db.Column(db.String(150), unique=True)
    recipes = db.relationship('Recipe') # relationship between user and recipe, one to many

    def __str__(self):
        return self.username

recipe_website/__init__.py
# setup Flask application

from flask import Flask, current_app
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
from dotenv import load_dotenv
import os

load_dotenv()

# access environment variables
SECRET_KEY = os.environ.get('SECRET_KEY')
DB_NAME = os.environ.get('DB_NAME')

db = SQLAlchemy() # database object

def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = SECRET_KEY
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app) # initialize database

    # register views for our application
    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    # script to check if database exists, if not, create it
    from .models import User, Recipe

    # create a database within Flask application context
    with app.app_context():
        create_database()

    # login manager
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader # decorator
    def load_user(id):
        return User.query.get(int(id)) # how to load a user from the database - id is a string, convert to int

    return app

"""
older version - create_all(app=app)
version 2.0.0, Flask-SQLAlchemy deprecated the app argument
use current application context - current_app proxy object
"""
def create_database():
    with current_app.app_context():
        if not path.exists('recipe_website/' + DB_NAME):
            db.create_all()
            print('Created Database!')

recipe_website/auth.py
# login - authorization
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['POST', 'GET']) # methods - allow user to send data to the server (POST) and to receive data from the server (GET)
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        # check if user email and password is valid - query
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True) # remember - keeps user logged in until they clears session/history
                return redirect(url_for('views.dashboard'))
            else:
                flash('Incorrect password, try again', category='error')
        else:
            flash('Email does not exist', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['POST', 'GET'])
def sign_up():
    if request.method == 'POST':
        email = request.form['email']
        username = request.form['username']
        password1 = request.form['password1']
        password2 = request.form['password2']

        user = User.query.filter_by(email=email).first() # check if user already exists
        if user:
            flash("Email already exists", category="error")
        elif len(email) < 3:
            flash("Email must be greater than 3 characters", category="error")
        elif len(username) < 2:
            flash("Username must be greater than 1 character", category="error")
        elif len(password1) < 8:
            flash("Password must be 8 characters or more", category="error")
        elif password1 != password2:
            flash("Passwords don't match", category="error")
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(password1, method='pbkdf2:sha256')) # method - hashing algorithm
            # add new user account to the database
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Account created", category="success")

            return redirect(url_for('auth.login')) # redirect to login page

    return render_template("sign_up.html", user=current_user)

recipe_website/views.py
# routes and views
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from .models import Recipe
from . import db
import json

# define our Blueprint
views = Blueprint('views', __name__)


@views.route('/')
def index():
    return render_template('index.html', user=current_user)

@views.route('/dashboard')
@login_required
def dashboard():
    user_recipes = Recipe.query.filter_by(user_id=current_user.id).all()
    return render_template('dashboard.html', recipes=user_recipes, user=current_user)

@views.route('/add_recipe', methods=['POST', 'GET'])
@login_required
def add_recipe():
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        ingredients = request.form['ingredients']
        instructions = request.form['instructions']

        # Create a new recipe instance
        recipe = Recipe(
            recipe_name=title,
            recipe_description=description,
            recipe_ingredients=ingredients,
            recipe_instructions=instructions,
            user_id=current_user.id
        )
        # Save the recipe to the database
        db.session.add(recipe)
        db.session.commit()
        return redirect(url_for('views.dashboard'))

    return render_template('add_recipe.html', user=current_user)

@views.route('/update_recipe/<int:id>', methods=['POST', 'GET'])
@login_required
def update_recipe(id):
    """ sending request as a form """
    recipe = Recipe.query.get_or_404(id)

    if request.method == 'POST':
        recipe.recipe_name = request.form['title']
        recipe.recipe_description = request.form['description']
        recipe.recipe_ingredients = request.form['ingredients']
        recipe.recipe_instructions = request.form['instructions']

        db.session.commit()
        flash('Recipe updated', 'success')
        return redirect(url_for('views.dashboard'))

    return render_template('update_recipe.html', recipe=recipe, user=current_user)

@views.route('/delete-recipe/<int:id>', methods=['POST', 'GET'])
@login_required
def delete_recipe(id):
    recipe = Recipe.query.get_or_404(id)
    if request.method == 'POST':
        db.session.delete(recipe)
        db.session.commit()
        flash('Recipe deleted successfully!', 'success')
        return redirect(url_for('views.dashboard'))
    return render_template('delete_recipe.html', recipe=recipe, user=current_user)

recipe_website/templates/add_recipe.html
{% extends 'index.html' %}

{% block content %}
    <h1 align="center">Add Recipe</h1>
    <form method="POST">
        <div class="mb-3">
            <label for="title" class="form-label">Title:</label>
            <input type="text" class="form-control" id="title" name="title" required>
        </div>

        <div class="mb-3">
            <label for="description" class="form-label">Description:</label>
            <textarea id="description" class="form-control" name="description" cols="50" rows="20" required></textarea>
        </div>

        <div class="mb-3">
            <label for="ingredients" class="form-label">Ingredients:</label>
            <textarea id="ingredients" class="form-control" name="ingredients" cols="50" rows="20" required></textarea>
        </div>

        <div class="mb-3">
            <label for="instructions" class="form-label">Instructions:</label>
            <textarea id="instructions" class="form-control" name="instructions" cols="50" rows="20" required></textarea>
        </div>

        <br>
        <!-- add an input field for image upload -->
        <button type="submit">Add Recipe</button>
    </form>
{% endblock %}

recipe_website/templates/dashboard.html
{% extends 'index.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <h1 align="center">Welcome {{ user }}</h1>
    <br>
    {% if recipes %}
    <h1>My Recipes:</h1>
    <ul class="list-group list-group-flush" id="recipes">
        {% for recipe in recipes %}
        <li class="list-group-item"> {{ recipe.recipe_name }}
            <span aria-hidden='true'>
                <a href="{{ url_for('views.update_recipe', id=recipe.id) }}">Edit</a>
            </span>
            <span aria-hidden='true'>
                <a href="{{ url_for('views.delete_recipe', id=recipe.id) }}">Delete</a>
            </span>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No recipes found</p>
    {% endif %}
    <a href="/add_recipe">Add Recipe</a>
{% endblock %}

recipe_website/templates/delete_recipe.html
{% extends 'index.html' %}

{% block title %}Delete Recipe{% endblock %}

{% block content %}
<h1 align="center">Delete Recipe</h1>
<p>Are you sure you want to delete "{{ recipe.recipe_name }}"?</p>
<form method="POST" action="{{ url_for('views.delete_recipe', id=recipe.id) }}">
    <button type="submit">Delete</button>
    <a href="{{ url_for('views.dashboard') }}">Cancel</a>
</form>
{% endblock %}

recipe_website/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <title>{% block title %}MealMaster{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">MealMaster</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="/profile">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/logout">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="/login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/sign-up">Sign Up</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endfor %}
        {% endif %}
        {% endwith %}


        <div class="container">
            {% block content %}
            <h1>Welcome to MealMaster!</h1>
            <p>MealMaster is a recipe management website that allows you to create, edit, and delete recipes.<br>You can also view other users' recipes and rate them.</p>
            <p>Click <a href="/sign-up">here</a> to sign up or <a href="/login">here</a> to login.</p>
            {% endblock %}

        </div>



        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"></script>

    </body>
</html>

recipe_website/templates/login.html
<!-- extend the base/index template-->
{% extends "index.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<form method="POST" action="">
    <h1 align="center">Login</h1>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email" required>
    </div>

    <div class="mb-3">
        <label for="password" class="form-label">Enter Password</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Login</button>
    <br>
    <a href="/sign-up">Don't have an account? Sign up here</a>
</form>
{% endblock %}

recipe_website/templates/sign_up.html
{% extends "index.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<form method="POST">
    <h1 align="center">Sign Up</h1>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email">
    </div>

    <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" id="username" name="username">
    </div>

    <div class="mb-3">
        <label for="password1" class="form-label">Enter Password</label>
        <input type="password" class="form-control" id="password1" name="password1">
    </div>

    <div class="mb-3">
        <label for="password2" class="form-label">Confirm Password</label>
        <input type="password" class="form-control" id="password2" name="password2">
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Sign Up</button>
    <br>
    <a href="/login">Already have an account? Login here</a>
</form>
{% endblock %}

recipe_website/templates/update_recipe.html
{% extends 'index.html' %}

{% block title %}Edit Recipe{% endblock %}

{% block content %}
<h1 align="center">Edit Recipe</h1>
<form method="POST" action="{{ url_for('views.update_recipe', id=recipe.id) }}">
    <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input type="text" class="form-control" id="title" name="title" value="{{ recipe.recipe_name }}">
    </div>

    <div class="mb-3">
        <label for="title" class="form-label">Description</label>
        <input type="text" class="form-control" id="description" name="description" value="{{ recipe.recipe_description }}">
    </div>

    <div class="mb-3">
        <label for="title" class="form-label">Ingredients</label>
        <input type="text" class="form-control" id="ingredients" name="ingredients" value="{{ recipe.recipe_ingredients }}">
    </div>

    <div class="mb-3">
        <label for="title" class="form-label">Instructions</label>
        <input type="text" class="form-control" id="instructions" name="instructions" value="{{ recipe.recipe_instructions }}">
    </div>
    <br>
    <button type="submit">Save Changes</button>
</form>
{% endblock %}